application: moneytowaste
version: 2
runtime: python
api_version: 1

handlers:
- url: /admin
  script: admin.py
- url: /s
  static_dir: static
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /_ah/mail/.+
  script: incoming_email.py
  login: admin
- url: .*
  script: main.py

inbound_services:
- mail
